# Generated by Django 4.2.18 on 2026-06-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_propromocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='propromocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
