# Generated by Django 4.2.18 on 2026-02-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_task_category_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='emoji',
            field=models.CharField(default='📁', max_length=10, verbose_name='Эмодзи'),
        ),
    ]
