# Generated by Django 4.2.18 on 2026-05-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
    ]
