# Generated by Django 4.2.18 on 2026-05-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_task_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('focus', 'Фокус (таймер)'), ('planned', 'Плановая')], default='focus', max_length=20, verbose_name='Источник создания'),
        ),
    ]
