# Generated by Django 4.2.18 on 2026-06-10 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0007_task_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название цели')),
                ('goal_type', models.CharField(choices=[('time', 'По времени (часы)'), ('tasks', 'По задачам (количество)')], default='time', max_length=10)),
                ('target_value', models.FloatField(verbose_name='Целевое значение')),
                ('period', models.CharField(choices=[('week', 'Неделя'), ('month', 'Месяц'), ('custom', 'Своя дата')], default='week', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн (для своей даты)')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Выполнена'), ('failed', 'Просрочена')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ['-created_at'],
            },
        ),
    ]
