# Generated by Django 4.2.18 on 2026-06-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='emoji',
            field=models.CharField(default='📁', max_length=4, verbose_name='Эмодзи'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название цели'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название задачи'),
        ),
    ]
