# Generated by Django 4.2.18 on 2026-06-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_category_description_alter_category_emoji_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
